USE master
GO

CREATE DATABASE ATS
ON  PRIMARY 
( NAME = N'ATS', FILENAME = N'D:\database\mssql\ats\ats.mdf', SIZE = 100MB, FILEGROWTH = 10% )
LOG ON 
( NAME = N'ATS_log', FILENAME = N'D:\database\mssql\ats\ats_log.ldf', SIZE = 50MB, FILEGROWTH = 10%)
GO

EXEC dbo.sp_dbcmptlevel @dbname=N'ATS', @new_cmptlevel=90
GO
ALTER DATABASE ATS SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE ATS SET ANSI_NULLS OFF 
GO
ALTER DATABASE ATS SET ANSI_PADDING OFF 
GO
ALTER DATABASE ATS SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE ATS SET ARITHABORT OFF 
GO
ALTER DATABASE ATS SET AUTO_CLOSE OFF 
GO
ALTER DATABASE ATS SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE ATS SET AUTO_SHRINK OFF 
GO
ALTER DATABASE ATS SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE ATS SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE ATS SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE ATS SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE ATS SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE ATS SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE ATS SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE ATS SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE ATS SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE ATS SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE ATS SET  READ_WRITE 
GO
ALTER DATABASE ATS SET RECOVERY SIMPLE 
GO
ALTER DATABASE ATS SET  MULTI_USER 
GO
ALTER DATABASE ATS SET PAGE_VERIFY CHECKSUM  
GO
USE ATS
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE ATS MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
