USE master
GO
CREATE LOGIN ats WITH PASSWORD=N'Passw0rd', DEFAULT_DATABASE=ATS, CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO
USE ATS
GO
CREATE USER ats FOR LOGIN ats
GO
EXEC sp_addrolemember N'db_owner', N'ats'
GO
